### PR TITLE
1.1.0

### PR DESCRIPTION
**Pull request by aditya7iyengar**
- [x] Minimize Meta-programming.

- [ ] Make it work with multiple css frameworks:
   - [x] Bootstrap
   - [ ] Foundation
   - [ ] Custom

- [x] Pagination
   - [x] Make it work with `Rummage.Ecto` 1.1.0.
   - [x] Clean up support for slug params
   - [x] Add maximum page links shown configuration
   - [x] Support for KeySet Pagination Hook.
   - [x] Add link options for an image or a character like "<<", ">>"

- [x] Sort
   - [x] Clean up and make it work with `Rummage.Ecto` 1.1.0.
   - [x] Add link options for image or a character.

- [x] Search
   - [x] Clean up and make it work with `Rummage.Ecto` 1.1.0.
   - [x] Nested Search associations
   - [ ] Minimum number of characters before search. 
   - [ ] Add support for slug params

- [x] Test Association search and sort (this should be fixed with `Rummage.Ecto` 1.1.0)

- [ ] Compatibility with Phnx 1.3

- [ ] Get test coverage up to ~95%

- [ ] Get docs on inch to ~95%

### CODE REVIEW

**Comment by agustif** [comment]
hi @aditya7iyengar how could one help you? I want to use this!

**Comment by aditya7iyengar** [comment]
Hi @agustif Thanks for offering! 😄 I was sick last week, so couldn't make much progress in this. I intend to wrap this up asap. I would probably need 4-5 hours to finish it. Hopefully, it wouldn't take too long.

**Comment by agustif** [comment]
@aditya7iyengar glad to see you are feeling better and have had some activity.

Cheers for the work! stay healthy!

**Comment by mackstar** [comment]
Hello, I am also keen to use this Where are we up to? I hope you are well again!

**Comment by aditya7iyengar** [comment]
@mackstar I have been waiting for more information on Phoenix 1.3 and the book to come out. I guess the wait has been too long, so I will go ahead and downgrade the elixir/phoenix version on this and get this out of the way. Sorry for the delay!

**Pull request merged**
