### PR TITLE
Allows usage of slugs and other params

### LINKED ISSUE #25: Struct opts for namespace does not support Nested namespace objects
I read the code for the pagination macros and this is what I found out:

The namespace being followed when passing a struct opt to the view is de-atomized into a string and converted to a URL helper

```ex
  use Rummage.Phoenix.View, helpers: Backroom.Router.Helpers, struct: :order
```

In turn, it will construct a function in the pagination_link/2 that tries to call a router helper by appending _path:

```ex
  Backroom.Router.Helpers.order_path/4
``` 

However, what I want to call is:

```ex
  Backroom.Router.Helpers.backroom_merchant_order_path/4
```

Replacing the struct with something does not exist does not work as well, even if does call the function I need.

```ex
  use Rummage.Phoenix.View, helpers: Backroom.Router.Helpers, struct: :backroom_merchant_order
```

The error of the above code results into Phoenix.Param not accepting maps, but only structs.

Any workaround for this?

### PR DESCRIPTION
**Pull request by jekku**
This adds the capability to add slugs to a certain url, and to put rummage params side by side with other extra params.

For example you can generate:

http://localhost:4000/people/aditya7iyengar/?rummage[paginate][page]=1&rummage[paginate][per_page]=5&another_param=somethingUsefulToAnExistingApp

This is done by passing an extra array of slugs / params required by the route helper, and a map of params that can be merged with the rummage params passed to the URL.

Fixes #25

### CODE REVIEW

**Comment by aditya7iyengar** [comment]
👍 Looks good to me. Thanks for the contribution @jekku!

**Comment by jekku** [comment]
@aditya7iyengar I hope you don't mind if I also do this for the search option so that they can work in conjunction. Thanks!

**Comment by aditya7iyengar** [comment]
@jekku I can wrap that up in [this](https://github.com/aditya7iyengar/rummage_phoenix/pull/28) PR. I'm cleaning up the module quite a bit to follow better practices. So it will be easy for me to do that while I'm working on it.

**Comment by jekku** [comment]
Amazing! :) Thanks man.

**Comment by jekku** [comment]
If possible, maybe it's good to add a pagination_link or search_form that directly accepts the helper function and its parameters :)

**Pull request merged**
